name: Test docker actions

on: 
  workflow_dispatch:
    inputs:
      url:
        type: choice
        options: 
          - 'https://www.google.com'
          - 'https://www.lnguyen.com'
          - 'abcxyz'
      max_trials:
        description: Maximum number of trial 
        default: '10'
        required: false 
      delay:
        description: Delay in second between trial 
        default: '5'
        required: false 

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
          delay: ${{ inputs.delay }}
          max_trials: ${{ inputs.max_trials }}